// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduiiJe_ugkWVMTNnV1pudSSpu19gf_xQ',
    appId: '1:846122534071:web:3d5d6c61b2c2be6638f932',
    messagingSenderId: '846122534071',
    projectId: 'tayarh-6e60b',
    authDomain: 'tayarh-6e60b.firebaseapp.com',
    storageBucket: 'tayarh-6e60b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxNs8ZKVbV2JVuR2k31cYu2fKLouF8P0w',
    appId: '1:846122534071:android:24806e7a2e9b2b3e38f932',
    messagingSenderId: '846122534071',
    projectId: 'tayarh-6e60b',
    storageBucket: 'tayarh-6e60b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWk9f1uKZyat9LndXre0908tIB405w6DY',
    appId: '1:846122534071:ios:390e5ba47c25ddb938f932',
    messagingSenderId: '846122534071',
    projectId: 'tayarh-6e60b',
    storageBucket: 'tayarh-6e60b.appspot.com',
    iosBundleId: 'com.example.tayarh',
  );
}
